### ISSUE TITLE
Need to scale internal dataset size

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/EDGAR-DOC-PARSER#116]
Could you expand the ```tikrs.txt``` list and confirm new added tickers work in our framework?

We will rapidly approach local memory limits from the download sizes. I believe the next steps are to enable programmatic off-loading of raw data after it is processed. 

My current machine sits at ~```6.4 GB``` memory used by 10 companies, but I believe the actual dataset I am using after processing is ~```130 MB```

**Comment by kamilkrukowski** [comment]
1. 
could you make a ```download_tikrs.sh``` shell script that downloads the tikr list at the URL you mentioned?
2.
could you make ```preprocess.py``` open ```tickers.json``` from ```1.``` and extract the tickers to use them?
3. 
could you update metadata query_server ONLY_IF metadata.is_processed is false or ```force == True```, and also make a ```parser.cleanup_raw()``` function that deletes outdated ```data/raw``` files? We should make ```featurize_file``` parsers call ```parser.cleanup_raw``` by default with some keyword argument to stop the behavior.
4. 
Currently, we use ```time.sleep``` to limit the number of requests per second in various scripts. Could we incorporate a new keyword argument to ```downloader.query_server``` called ```api_usage_delay``` or something similar and add ```time.sleep``` to the actual download function itself with some default sleep time?
5.
We need documentation, especially for the new parser. Check the website, the new parser added some broken documentation with undocumented function parameters. We probably need more internal documentation of the parser stuff you've added so that the rest of the team can better understand it.

**Comment by kamilkrukowski** [comment]
If I can help at all, feel free to ping or message me.

**Comment by NC-Zhao** [comment]
In `3`, I thought that the goal is to clean the `raw` and `parsed` folder after html files are generated and saved under `processed`. If this is the case, isn't it be more reasonable to make the clean step as a part of the `download.py` instead of as a part of the parser?

**Comment by kamilkrukowski** [comment]
We are thinking different things because no one has written down what the folders mean and where they come from.
See point 5.
We need a document that tracks these things.

In any case ```parser.featurize_file``` generates the contents of one of the three directories, one file at a time. The downloader does not control all the directories under the ```data_dir```, therefore the ```downloader.py``` cannot track when to delete ```raw``` or etc. (Unless we do a complicated code base rewrite)

In any case,
Please re-confirm but I believe ```raw``` is downloaded, some other folder is extracted, and finally a third folder contains the regex-parsed data frames. Please type up the folder structure in a word document that can later be placed in the documentation.

**Comment by kamilkrukowski** [comment]
@NC-Zhao Could we have an ETA for the memory fixes in whatever form they take? ```3```.

```1,2,4``` can be pull-requested early as they should be quick fixes.

**Comment by NC-Zhao** [comment]
@kamilkrukowski where to put `download_tikrs.sh`? In `2`, we no longer have the `preprocessor.py`, is it now incorporated in `downloader.py` or somewhere else?

**Comment by kamilkrukowski** [comment]
TBH we probably want ```metadata_mgr``` helper functions like 'download all tiers to data/metadata/tikrs.json' and 'return list of all tikrs'

**Comment by NC-Zhao** [comment]
@kamilkrukowski For part 3, here is what I have about the generation of data folder:
- `query_server` saves raw data downloaded from EDGAR to `data\raw`
- `unpack_bulk` calls `unpack_file` and save processed .html files to `data\process`
- `parser.featureize_file` calls `save_processed` save featurized .pkl files into `data\parsed`
If I'm right, we want to keep the html files and the parsed features. So my call would be to clean the raw data after unpacked.

**Comment by kamilkrukowski** [comment]
We should have a metadata.is_tikr_unpacked/process metadata tag.

Currently, ```query_server``` will abort if some metadata.is_tikr_downloaded tag is True and the force kwarg is False.
This 'progress tracking' and abort behavior should be maintained and the relevant metadata updated if we delete files when using ```unpack_bulk```. I think ```unpack_bulk``` can delete files when finished IF some kwarg is set to do so.

I think we should add the similar kwarg functionality to ```parser.featurize_file``` to allow deletion after ```save_processed``` succeeds.

**Comment by NC-Zhao** [comment]
@kamilkrukowski I just commit to the `dataset_scale` branch regarding the used file remove. And I need your help on update the metadata when files are deleted, if needed. And I will be working on the documentations tonight.

**Comment by kamilkrukowski** [comment]
I have created a style-branch called ```flake8```. If you could check it out, add the necessary changes, and recommit that would be helpful.

We should merge ```dataset_scale``` into ```main``` and rebase ```flake8``` on main before developing on ```flake8``` due to every file having newline/spaces changed and massive merge conflicts

**Comment by kamilkrukowski** [comment]
Could you set up a series of pull requests for ```1```, ```3```, ```4```?

**Comment by NC-Zhao** [comment]
TBH, I don't understand the changes made on `flake8`, are you asking me to check if the parser of it align with the `dataset_scale`? @kamilkrukowski

**Comment by kamilkrukowski** [comment]
The pull request is good.

The flake8 changes enforce python best practice coding styles for readability.
However, some of the file documentation is still improperly formatted. The flake8 changes prevent commits being made locally if they do not follow guidelines. That means if the flake8 branch is checked out, it will prevent further development until the current formatting issues are fixed. Once the issues are fixed, a 'clean flake8' commit can be pushed and that can be a new merge point into main.

Flake8 is an automated style checker

**Comment by kamilkrukowski** [comment]
too long of an issue history
